"""
Audit CEREBRO theme presets for WCAG 2.1 contrast (informative, not legal advice).

Checks normal text (AA 4.5:1): text_primary, text_secondary, text_muted vs bg_base;
accent_primary vs bg_base, bg_panel, and bg_sidebar.

Usage:
  python -m dedup.scripts.audit_theme_contrast
  python -m dedup.scripts.audit_theme_contrast --md-out docs/THEME_CONTRAST_REPORT.md
  python -m dedup.scripts.audit_theme_contrast --strict  # exit 1 if any pair fails AA normal
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Tuple

_root = Path(__file__).resolve().parent.parent
if str(_root) not in sys.path:
    sys.path.insert(0, str(_root))

from dedup.ui.theme.contrast import contrast_ratio, format_ratio, passes_aa_normal
from dedup.ui.theme.theme_registry import THEMES


def _check_pair(
    theme_key: str,
    label: str,
    fg: str,
    bg: str,
    failures: List[str],
) -> Tuple[str, str, str]:
    r = contrast_ratio(fg, bg)
    ok = passes_aa_normal(r)
    if not ok:
        failures.append(f"{theme_key} {label} {fg} on {bg} => {format_ratio(r)}")
    status = "PASS" if ok else "FAIL"
    return label, format_ratio(r), status


def run_audit() -> Tuple[List[str], str]:
    failures: List[str] = []
    lines: List[str] = []
    lines.append("# Theme contrast audit (WCAG AA normal text 4.5:1)")
    lines.append("")
    lines.append("Generated by `python -m dedup.scripts.audit_theme_contrast`. Not a compliance certificate.")
    lines.append("")

    for key in sorted(THEMES.keys()):
        t = THEMES[key]
        name = t.get("name", key)
        lines.append(f"## {name} (`{key}`)")
        lines.append("")
        lines.append("| Check | Ratio | AA |")
        lines.append("|-------|-------|-----|")
        bg_base = t["bg_base"]
        bg_panel = t.get("bg_panel", bg_base)
        bg_sidebar = t.get("bg_sidebar", bg_base)
        pairs = [
            ("text_primary / bg_base", t["text_primary"], bg_base),
            ("text_secondary / bg_base", t.get("text_secondary", "#888"), bg_base),
            ("text_muted / bg_base", t.get("text_muted", "#888"), bg_base),
            ("accent / bg_base", t.get("accent_primary", "#000"), bg_base),
            ("accent / bg_panel", t.get("accent_primary", "#000"), bg_panel),
            ("accent / bg_sidebar", t.get("accent_primary", "#000"), bg_sidebar),
        ]
        for lbl, fg, bg in pairs:
            _, ratio_s, status = _check_pair(key, lbl, fg, bg, failures)
            lines.append(f"| {lbl} | {ratio_s} | {status} |")
        lines.append("")

    return failures, "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Audit theme token contrast ratios.")
    ap.add_argument("--md-out", type=Path, default=None, help="Write Markdown report to this path")
    ap.add_argument("--strict", action="store_true", help="Exit 1 if any check fails AA normal (4.5:1)")
    args = ap.parse_args()

    failures, md = run_audit()
    if args.md_out:
        args.md_out.parent.mkdir(parents=True, exist_ok=True)
        args.md_out.write_text(md, encoding="utf-8")
        print(f"Wrote {args.md_out}")
    else:
        print(md)

    if failures:
        print("\n--- Failures ---", file=sys.stderr)
        for f in failures:
            print(f, file=sys.stderr)
        if args.strict:
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
